// ============================================================
// IMPORTS
// ============================================================

// useSelector - a hook that lets this component READ data from the redux store
// useDispatch - a hook that lets this component SEND actions to the redux store
import { useSelector, useDispatch } from 'react-redux'

// import the action creators that were auto-generated by createSlice
// these are the functions we will pass into dispatch() to change the state
// increment, decrement, incrementByAmount all come from counterSlice.actions
import { increment, decrement, incrementByAmount } from '../redux/counterSlice'

// ============================================================
// COMPONENT
// ============================================================

export default function Counter() {

  // ============================================================
  // useSelector
  // ============================================================
  // useSelector is a hook that takes a callback function as an argument
  // the callback function receives the ENTIRE redux store as "state"
  // we then use dot notation to drill down to the exact piece of data we want
  //
  // state                = the entire redux store (all slices combined)
  // state.counter        = the counter slice (named "counter" in store.js reducer object)
  // state.counter.count  = the count property inside counterSlice's initialState
  //
  // whenever state.counter.count changes in the store,
  // useSelector will automatically cause this component to re-render
  // so the UI always shows the latest value
  const count = useSelector(state => state.counter.count)
  
  // ============================================================
  // useDispatch
  // ============================================================
  // useDispatch is a hook that returns the dispatch function from the redux store
  // we store it in a variable called dispatch so we can call it later
  // dispatch is the only way to trigger a state change in redux
  // you cannot change the store directly - you MUST go through dispatch
  const dispatch = useDispatch()

  // ============================================================
  // JSX / TEMPLATE
  // ============================================================
  return (
    <div>
      {/* count is the value we read from the store using useSelector above */}
      {/* it will automatically update every time the store changes */}
      <h1>Count is {count}</h1>

      {/* ======================================================
          INCREMENT BUTTON
          ======================================================
          onClick fires an arrow function when the button is clicked
          the arrow function calls dispatch() with the increment() action creator
          increment() returns an action object that looks like: { type: 'counter/increment' }
          dispatch sends that action object to the redux store
          the store finds the matching reducer (increment in counterSlice)
          the reducer runs: state.count += 1
          the store updates, useSelector detects the change, component re-renders */}
      <button onClick={() => dispatch(increment())}>Increment</button>

      {/* ======================================================
          DECREMENT BUTTON
          ======================================================
          same flow as increment but calls the decrement action creator
          decrement() returns an action object: { type: 'counter/decrement' }
          dispatch sends it to the store
          the matching reducer runs: state.count -= 1
          store updates, component re-renders with new count */}
      <button onClick={() => dispatch(decrement())}>Decrement</button>

      {/* ======================================================
          INCREMENT BY AMOUNT BUTTON
          ======================================================
          incrementByAmount is different because it accepts an argument (5)
          the argument becomes action.payload inside the reducer
          incrementByAmount(5) returns: { type: 'counter/incrementByAmount', payload: 5 }
          dispatch sends it to the store
          the matching reducer runs: state.count += action.payload (which is 5)
          store updates, component re-renders with new count */}
      <button onClick={() => dispatch(incrementByAmount(20))}>Add 5</button>
    </div>
  )
}