// ============================================================
// IMPORTS
// ============================================================

// useSelector - lets this component READ data from the Redux store
// useDispatch - lets this component SEND actions to the Redux store
import { useSelector, useDispatch } from 'react-redux'

// import the actions we need from counterSlice
// increment - adds 1 to count
// decrement - subtracts 1 from count
// these were auto-generated by createSlice in counterSlice.js
import { increment, decrement } from '../redux/counterSlice'

// ============================================================
// COMPONENT
// ============================================================

export default function Counter2() {

  // ============================================================
  // useSelector - READ state from Redux store
  // ============================================================
  // state                = the entire Redux store (all slices)
  // state.counter        = our counter slice (named "counter" in store.js)
  // state.counter.count  = the actual count number inside the slice
  // whenever count changes in the store, this component auto re-renders
  const count = useSelector(state => state.counter.count)

  // ============================================================
  // useDispatch - SEND actions to Redux store
  // ============================================================
  // useDispatch returns the dispatch function
  // dispatch is the ONLY way to update state in Redux
  // you cannot change the store directly - must go through dispatch
  const dispatch = useDispatch()

  // ============================================================
  // JSX / TEMPLATE
  // ============================================================
  return (
    <div>

      {/* count comes from the Redux store via useSelector above
          it is the SAME count that Counter.js reads
          both components share the same state! */}
      <h1>Counter2 is {count}</h1>

      {/* ======================================================
          INCREMENT BUTTON
          ======================================================
          onClick fires dispatch(increment()) when clicked
          increment() returns action object: { type: 'counter/increment' }
          dispatch sends it to the Redux store
          the reducer runs: state.count += 1
          store updates --> useSelector detects change --> re-renders */}
      <button onClick={() => dispatch(increment())}>Increment</button>

      {/* ======================================================
          DECREMENT BUTTON
          ======================================================
          onClick fires dispatch(decrement()) when clicked
          decrement() returns action object: { type: 'counter/decrement' }
          dispatch sends it to the Redux store
          the reducer runs: state.count -= 1
          store updates --> useSelector detects change --> re-renders */}
      <button onClick={() => dispatch(decrement())}>Decrement</button>

    </div>
  )
}